In [1]:
import numpy as np

In [2]:
matrix=np.array([[105,2.025,2.5,2.4,0.36,80,100,30,6,1.24,8,3.8],[80,2.025,4.8,3.5,0.3,40,110,40,8,2,6,2.02],[130,2.022,5.03,2.25,0.34,50,122,35,6,1.27,4,7.6],[200,2.02,2.15,2.14,0.35,45,98,45,6,1.12,5,4.1],[125,2.025,6,1.5,0.39,80,95,43.8,6,1.29,3,9.1],[250,2.025,2.41,0.015,0.38,40,65,26.8,4,1.19,4,3.91]])
print(matrix)

[[1.050e+02 2.025e+00 2.500e+00 2.400e+00 3.600e-01 8.000e+01 1.000e+02
  3.000e+01 6.000e+00 1.240e+00 8.000e+00 3.800e+00]
 [8.000e+01 2.025e+00 4.800e+00 3.500e+00 3.000e-01 4.000e+01 1.100e+02
  4.000e+01 8.000e+00 2.000e+00 6.000e+00 2.020e+00]
 [1.300e+02 2.022e+00 5.030e+00 2.250e+00 3.400e-01 5.000e+01 1.220e+02
  3.500e+01 6.000e+00 1.270e+00 4.000e+00 7.600e+00]
 [2.000e+02 2.020e+00 2.150e+00 2.140e+00 3.500e-01 4.500e+01 9.800e+01
  4.500e+01 6.000e+00 1.120e+00 5.000e+00 4.100e+00]
 [1.250e+02 2.025e+00 6.000e+00 1.500e+00 3.900e-01 8.000e+01 9.500e+01
  4.380e+01 6.000e+00 1.290e+00 3.000e+00 9.100e+00]
 [2.500e+02 2.025e+00 2.410e+00 1.500e-02 3.800e-01 4.000e+01 6.500e+01
  2.680e+01 4.000e+00 1.190e+00 4.000e+00 3.910e+00]]


In [3]:
matrix_squared=matrix**2
print(matrix_squared)

[[1.102500e+04 4.100625e+00 6.250000e+00 5.760000e+00 1.296000e-01
  6.400000e+03 1.000000e+04 9.000000e+02 3.600000e+01 1.537600e+00
  6.400000e+01 1.444000e+01]
 [6.400000e+03 4.100625e+00 2.304000e+01 1.225000e+01 9.000000e-02
  1.600000e+03 1.210000e+04 1.600000e+03 6.400000e+01 4.000000e+00
  3.600000e+01 4.080400e+00]
 [1.690000e+04 4.088484e+00 2.530090e+01 5.062500e+00 1.156000e-01
  2.500000e+03 1.488400e+04 1.225000e+03 3.600000e+01 1.612900e+00
  1.600000e+01 5.776000e+01]
 [4.000000e+04 4.080400e+00 4.622500e+00 4.579600e+00 1.225000e-01
  2.025000e+03 9.604000e+03 2.025000e+03 3.600000e+01 1.254400e+00
  2.500000e+01 1.681000e+01]
 [1.562500e+04 4.100625e+00 3.600000e+01 2.250000e+00 1.521000e-01
  6.400000e+03 9.025000e+03 1.918440e+03 3.600000e+01 1.664100e+00
  9.000000e+00 8.281000e+01]
 [6.250000e+04 4.100625e+00 5.808100e+00 2.250000e-04 1.444000e-01
  1.600000e+03 4.225000e+03 7.182400e+02 1.600000e+01 1.416100e+00
  1.600000e+01 1.528810e+01]]


In [4]:
matrix_squared_sum=np.sqrt(np.sum(matrix_squared,axis=0))
print(matrix_squared_sum)

[390.44846011   4.9569531   10.05094523   5.46830184   0.86844689
 143.26548782 244.61806965  91.57881851  14.96662955   3.38896739
  12.88409873  13.82709297]


In [5]:
Normalized_decision_Matrix=matrix / matrix_squared_sum
print(Normalized_decision_Matrix)

[[0.26892154 0.40851708 0.24873282 0.43889311 0.41453312 0.55840385
  0.40880054 0.32758667 0.40089186 0.36589316 0.62092042 0.27482277]
 [0.2048926  0.40851708 0.47756702 0.64005245 0.34544427 0.27920193
  0.4496806  0.43678222 0.53452248 0.59015026 0.46569032 0.14609   ]
 [0.33295047 0.40791187 0.50045044 0.41146229 0.3915035  0.34900241
  0.49873666 0.38218445 0.40089186 0.37474542 0.31046021 0.54964554]
 [0.5122315  0.40750839 0.21391023 0.39134636 0.40301831 0.31410217
  0.40062453 0.49138    0.40089186 0.33048415 0.38807526 0.29651931]
 [0.32014469 0.40851708 0.59695878 0.27430819 0.44907755 0.55840385
  0.38836052 0.47827654 0.40089186 0.38064692 0.23284516 0.65812821]
 [0.64028937 0.40851708 0.23977844 0.00274308 0.43756274 0.27920193
  0.26572035 0.29264409 0.26726124 0.35113941 0.31046021 0.28277817]]


In [6]:
criteria_weights= np.array([0.076,0.043,0.113,0.075,0.025,0.205,0.064,0.072,0.208,0.056,0.035,0.035])

In [7]:
weighted_normalized_matrix = criteria_weights*Normalized_decision_Matrix
print(weighted_normalized_matrix)

[[0.02043804 0.01756623 0.02810681 0.03291698 0.01036333 0.11447279
  0.02616323 0.02358624 0.08338551 0.02049002 0.02173221 0.0096188 ]
 [0.01557184 0.01756623 0.05396507 0.04800393 0.00863611 0.05723639
  0.02877956 0.03144832 0.11118068 0.03304841 0.01629916 0.00511315]
 [0.02530424 0.01754021 0.0565509  0.03085967 0.00978759 0.07154549
  0.03191915 0.02751728 0.08338551 0.02098574 0.01086611 0.01923759]
 [0.03892959 0.01752286 0.02417186 0.02935098 0.01007546 0.06439094
  0.02563997 0.03537936 0.08338551 0.01850711 0.01358263 0.01037818]
 [0.024331   0.01756623 0.06745634 0.02057311 0.01122694 0.11447279
  0.02485507 0.03443591 0.08338551 0.02131623 0.00814958 0.02303449]
 [0.04866199 0.01756623 0.02709496 0.00020573 0.01093907 0.05723639
  0.0170061  0.02107037 0.05559034 0.01966381 0.01086611 0.00989724]]


In [8]:
a,b,c,d,e,f=weighted_normalized_matrix[:1],weighted_normalized_matrix[1:2],weighted_normalized_matrix[2:3],weighted_normalized_matrix[3:4],weighted_normalized_matrix[4:5],weighted_normalized_matrix[5:6]



In [9]:
for i,j in zip(a,b):
    c12=(i>j)
for i,j in zip(a,c):
    c13=(i>j)
for i,j in zip(a,d):
    c14=(i>j)
for i,j in zip(a,e):
    c15=(i>j)
for i,j in zip(a,f):
    c16=(i>j)
    
for i,j in zip(b,a):
    c21=(i>j)
for i,j in zip(b,c):
    c23=(i>j)
for i,j in zip(b,d):
    c24=(i>j)
for i,j in zip(b,e):
    c25=(i>j)
for i,j in zip(b,f):
    c26=(i>j)
    
for i,j in zip(c,a):
    c31=(i>j)
for i,j in zip(c,b):
    c32=(i>j)
for i,j in zip(c,d):
    c34=(i>j)
for i,j in zip(c,e):
    c35=(i>j)
for i,j in zip(c,f):
    c36=(i>j)
    
for i,j in zip(d,a):
    c41=(i>j)
for i,j in zip(d,b):
    c42=(i>j)
for i,j in zip(d,c):
    c43=(i>j)
for i,j in zip(d,e):
    c45=(i>j)
for i,j in zip(d,f):
    c46=(i>j)
    
for i,j in zip(e,a):
    c51=(i>j)
for i,j in zip(e,b):
    c52=(i>j)
for i,j in zip(e,c):
    c53=(i>j)
for i,j in zip(e,d):
    c54=(i>j)
for i,j in zip(e,f):
    c56=(i>j)

for i,j in zip(f,a):
    c61=(i>j)
for i,j in zip(f,b):
    c62=(i>j)
for i,j in zip(f,c):
    c63=(i>j)
for i,j in zip(f,d):
    c64=(i>j)
for i,j in zip(f,e):
    c65=(i>j)

print(c21*1)

[0 0 1 1 0 0 1 1 1 1 0 0]


In [10]:
d1={1:0.076,2:0.043,3:0.113,4:0.075,5:0.025,6:0.205,7:0.064,8:0.072,9:0.208,10:0.056,11:0.035,12:0.035}

In [11]:
A1=[[0,d1[1]+d1[5]+d1[6]+d1[11]+d1[12],d1[2]+d1[4]+d1[5]+d1[6]+d1[11],d1[2]+d1[3]+d1[4]+d1[5]+d1[6]+d1[7]+d1[10]+d1[11],d1[4]+d1[7]+d1[11],d1[3]+d1[4]+d1[6]+d1[7]+d1[8]+d1[9]+d1[10]+d1[11]]]
A2=[[d1[3]+d1[4]+d1[7]+d1[8]+d1[9]+d1[10],0,d1[2]+d1[4]+d1[8]+d1[9]+d1[10]+d1[11],d1[2]+d1[3]+d1[4]+d1[7]+d1[9]+d1[10]+d1[11],d1[4]+d1[7]+d1[9]+d1[10]+d1[11],d1[3]+d1[4]+d1[7]+d1[8]+d1[9]+d1[10]+d1[11]]]
A3=[[d1[1]+d1[3]+d1[7]+d1[8]+d1[10]+d1[12],d1[1]+d1[3]+d1[5]+d1[6]+d1[7]+d1[12],0,d1[2]+d1[3]+d1[4]+d1[6]+d1[7]+d1[10]+d1[12],d1[1]+d1[4]+d1[7]+d1[11],+d1[3]+d1[4]+d1[6]+d1[7]+d1[8]+d1[9]+d1[10]+d1[12]]]
A4=[[d1[1]+d1[8]+d1[12],d1[1]+d1[5]+d1[6]+d1[8]+d1[12],d1[1]+d1[5]+d1[8]+d1[11],0,d1[1]+d1[4]+d1[7]+d1[8]+d1[11],d1[4]+d1[6]+d1[7]+d1[8]+d1[9]+d1[11]+d1[12]]]
A5=[[d1[1]+d1[3]+d1[5]+d1[8]+d1[10]+d1[12],d1[1]+d1[3]+d1[5]+d1[6]+d1[8]+d1[12],d1[2]+d1[3]+d1[5]+d1[6]+d1[8]+d1[10]+d1[12],d1[2]+d1[3]+d1[5]+d1[6]+d1[10]+d1[12],0,d1[3]+d1[4]+d1[5]+d1[6]+d1[7]+d1[8]+d1[9]+d1[10]+d1[12]]]
A6=[[d1[1]+d1[5]+d1[12],d1[1]+d1[5]+d1[12],d1[1]+d1[2]+d1[5],d1[1]+d1[2]+d1[3]+d1[5]+d1[10],d1[1]+d1[11],0]]

In [12]:
new=np.concatenate((A1,A2,A3,A4,A5,A6),axis=0)
concordance_interval_matrix=new.reshape(6,6)
concordance_interval_matrix_copy=concordance_interval_matrix.copy()
print(concordance_interval_matrix)

[[0.    0.376 0.383 0.616 0.174 0.828]
 [0.588 0.    0.489 0.594 0.438 0.623]
 [0.416 0.518 0.    0.591 0.25  0.828]
 [0.183 0.413 0.208 0.    0.322 0.694]
 [0.377 0.526 0.549 0.477 0.    0.853]
 [0.136 0.136 0.144 0.313 0.111 0.   ]]


In [13]:
ab=np.sum(concordance_interval_matrix,axis=0)

c_bar=sum(ab)/(30)
print(ab)
print(c_bar)

[1.7   1.969 1.773 2.591 1.295 3.826]
0.43846666666666667


In [14]:
 for i in range(len(concordance_interval_matrix)):
        for j in range(len(concordance_interval_matrix)):
            if(concordance_interval_matrix[i][j]>=c_bar):
                concordance_interval_matrix[i][j]=1
            else:
                concordance_interval_matrix[i][j]=0
print(concordance_interval_matrix)            

[[0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
print(weighted_normalized_matrix)
g,h,i,j,k,l=weighted_normalized_matrix    #before --> e,f,g,h=weighted_normalized_matrix
print(g,h)

[[0.02043804 0.01756623 0.02810681 0.03291698 0.01036333 0.11447279
  0.02616323 0.02358624 0.08338551 0.02049002 0.02173221 0.0096188 ]
 [0.01557184 0.01756623 0.05396507 0.04800393 0.00863611 0.05723639
  0.02877956 0.03144832 0.11118068 0.03304841 0.01629916 0.00511315]
 [0.02530424 0.01754021 0.0565509  0.03085967 0.00978759 0.07154549
  0.03191915 0.02751728 0.08338551 0.02098574 0.01086611 0.01923759]
 [0.03892959 0.01752286 0.02417186 0.02935098 0.01007546 0.06439094
  0.02563997 0.03537936 0.08338551 0.01850711 0.01358263 0.01037818]
 [0.024331   0.01756623 0.06745634 0.02057311 0.01122694 0.11447279
  0.02485507 0.03443591 0.08338551 0.02131623 0.00814958 0.02303449]
 [0.04866199 0.01756623 0.02709496 0.00020573 0.01093907 0.05723639
  0.0170061  0.02107037 0.05559034 0.01966381 0.01086611 0.00989724]]
[0.02043804 0.01756623 0.02810681 0.03291698 0.01036333 0.11447279
 0.02616323 0.02358624 0.08338551 0.02049002 0.02173221 0.0096188 ] [0.01557184 0.01756623 0.05396507 0.048003

In [16]:
d1=abs(g-h)
d12=max(d1[1],d1[2],d1[3],d1[6],d1[7],d1[8],d1[9])/max(d1)

d2=abs(g-i)
d13=max(d2[0],d2[2],d2[6],d2[7],d2[8],d2[9],d2[11])/max(d2)

d3=abs(g-j)
d14=max(d3[0],d3[7],d3[8],d3[11])/max(d3)

d4=abs(g-k)
d15=max(d4[0],d4[1],d4[2],d4[4],d4[5],d4[7],d4[8],d4[9],d4[11])/max(d4)

d5=abs(g-l)
d16=max(d5[0],d5[1],d5[4],d5[11])/max(d5)

d6=abs(h-g)
d21=max(d6[0],d6[1],d6[4],d6[5],d6[10],d6[11])/max(d6)

d7=abs(h-i)
d23=max(d7[0],d7[2],d7[4],d7[5],d7[6],d7[11])/max(d7)

d8=abs(h-j)
d24=max(d8[0],d8[4],d8[5],d8[7],d8[11])/max(d8)

d9=abs(h-k)
d25=max(d9[0],d9[1],d9[2],d9[4],d9[5],d9[7],d9[11])/max(d9)

d_10=abs(h-l)
d26=max(d_10[0],d_10[1],d_10[4],d_10[5],d_10[11])/max(d_10)

d_11=abs(i-g)
d31=max(d_11[1],d_11[3],d_11[4],d_11[5],d_11[8],d_11[10])/max(d_11)

d_12=abs(i-h)
d32=max(d_12[1],d_12[3],d_12[7],d_12[8],d_12[9],d_12[10])/max(d_12)

d_13=abs(i-j)
d34=max(d_13[4],d_13[7],d_13[8],d_13[10])/max(d_13)

d_14=abs(i-k)
d35=max(d_14[1],d_14[2],d_14[4],d_14[5],d_14[7],d_14[8],d_14[9],d_14[11])/max(d_14)

d_15=abs(i-l)
d36=max(d_15[0],d_15[1],d_15[4],d_15[10])/max(d_15)

d_16=abs(j-g)
d41=max(d_16[1],d_16[2],d_16[3],d_16[4],d_16[5],d_16[6],d_16[8],d_16[9],d_16[10])/max(d_16)

d_17=abs(j-h)
d42=max(d_17[1],d_17[2],d_17[3],d_17[6],d_17[8],d_17[9],d_17[10])/max(d_17)

d_18=abs(j-i)
d43=max(d_18[1],d_18[2],d_18[3],d_18[5],d_18[6],d_18[8],d_18[9],d_18[11])/max(d_18)

d_19=abs(j-k)
d45=max(d_19[1],d_19[2],d_19[4],d_19[5],d_19[8],d_19[9],d_19[11])/max(d_19)

d_20=abs(j-l)
d46=max(d_20[0],d_20[1],d_20[2],d_20[4],d_20[9])/max(d_20)

d_21=abs(k-g)
d51=max(d_21[1],d_21[3],d_21[5],d_21[6],d_21[8],d_21[10])/max(d_21)

d_22=abs(k-h)
d52=max(d_22[1],d_22[3],d_22[6],d_22[8],d_22[9],d_22[10])/max(d_22)

d_23=abs(k-i)
d53=max(d_23[0],d_23[3],d_23[6],d_23[8],d_23[10])/max(d_23)

d_24=abs(k-j)
d54=max(d_24[0],d_24[3],d_24[6],d_24[7],d_24[8],d_24[10])/max(d_24)

d_25=abs(k-l)
d56=max(d_25[0],d_25[1],d_25[10])/max(d_25)

d_26=abs(l-g)
d61=max(d_26[1],d_26[2],d_26[3],d_26[5],d_26[6],d_26[7],d_26[8],d_26[9],d_26[10])/max(d_26)

d_27=abs(l-h)
d62=max(d_27[1],d_27[2],d_27[3],d_27[5],d_27[6],d_27[7],d_27[8],d_27[9],d_27[10])/max(d_27)

d_28=abs(l-i)
d63=max(d_28[2],d_28[3],d_28[5],d_28[6],d_28[7],d_28[8],d_28[9],d_28[10],d_28[11])/max(d_28)

d_29=abs(l-j)
d64=max(d_29[3],d_29[5],d_29[6],d_29[7],d_29[8],d_29[10],d_29[11])/max(d_29)

d_30=abs(l-k)
d65=max(d_30[1],d_30[2],d_30[3],d_30[4],d_30[5],d_30[6],d_30[7],d_30[8],d_30[9],d_30[11])/max(d_30)



In [17]:
discordance_interval_matrix=np.array((0,d12,d13,d14,d15,d16,d21,0,d23,d24,d25,d26,d31,d32,0,d34,d35,d36,d41,d42,d43,0,d45,d46,d51,d52,d53,d54,0,d56,d61,d62,d63,d64,d65,0))
discordance_interval_matrix=discordance_interval_matrix.reshape(6,6)
discordance_interval_matrix_copy=discordance_interval_matrix.copy()

print(discordance_interval_matrix)

[[0.         0.48562054 0.66261082 0.36922675 1.         0.49311204]
 [1.         0.         0.51480524 0.78399576 1.         0.59525011]
 [1.         1.         0.         0.24281384 1.         0.76198217]
 [1.         1.         1.         0.         1.         0.33392748]
 [0.34517905 0.48562054 0.23962742 0.2914948  0.         0.42509659]
 [1.         1.         1.         1.         1.         0.        ]]


In [18]:
bc=np.sum(discordance_interval_matrix,axis=0)

c_dash=sum(bc)/(30)
print(bc)
print(c_dash)

[4.34517905 3.97124109 3.41704348 2.68753115 5.         2.6093684 ]
0.734345439042364


In [19]:
for i in range(len(discordance_interval_matrix)):
        for j in range(len(discordance_interval_matrix)):
            if(discordance_interval_matrix[i][j]>=c_dash):
                discordance_interval_matrix[i][j]=0
            else:
                discordance_interval_matrix[i][j]=1
print(discordance_interval_matrix)            

[[1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1.]]


In [20]:
print(concordance_interval_matrix_copy)
print(discordance_interval_matrix_copy)

[[0.    0.376 0.383 0.616 0.174 0.828]
 [0.588 0.    0.489 0.594 0.438 0.623]
 [0.416 0.518 0.    0.591 0.25  0.828]
 [0.183 0.413 0.208 0.    0.322 0.694]
 [0.377 0.526 0.549 0.477 0.    0.853]
 [0.136 0.136 0.144 0.313 0.111 0.   ]]
[[0.         0.48562054 0.66261082 0.36922675 1.         0.49311204]
 [1.         0.         0.51480524 0.78399576 1.         0.59525011]
 [1.         1.         0.         0.24281384 1.         0.76198217]
 [1.         1.         1.         0.         1.         0.33392748]
 [0.34517905 0.48562054 0.23962742 0.2914948  0.         0.42509659]
 [1.         1.         1.         1.         1.         0.        ]]


In [21]:
col_sum_con=np.sum(concordance_interval_matrix_copy,axis=0)
row_sum_con=np.sum(concordance_interval_matrix_copy,axis=1)
net_superior_values=row_sum_con-col_sum_con

col_sum_disc=np.sum(discordance_interval_matrix_copy,axis=0)
row_sum_disc=np.sum(discordance_interval_matrix_copy,axis=1)
net_inferior_values=row_sum_disc-col_sum_disc

print("Net Superior Values are - : ",end="")
print(net_superior_values)
print("Net Inferior Values are - : ",end="")
print(net_inferior_values)


Net Superior Values are - : [ 0.677  0.763  0.83  -0.771  1.487 -2.986]
Net Inferior Values are - : [-1.33460888 -0.07718999  0.58775253  1.64639633 -3.21298159  2.3906316 ]


In [232]:
materials=["ABS - acrylonitrile-butadiene-styrene","PLA - polyactic acid","PC - poly carbonate","ASA - acrylonitrile styrene acrylate", "NYLON", "TPU ELASTOMER"]

In [233]:
print("The Most suitable material for manufacturing of spur gear is {}".format(materials[np.argmax(net_superior_values)]))
print("The Most suitable material for manufacturing of spur gear is {}".format(materials[np.argmin(net_inferior_values)]))

The Most suitable material for manufacturing of spur gear is NYLON
The Most suitable material for manufacturing of spur gear is NYLON
